# Generated by Django 4.0.4 on 2022-04-16 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='updatedat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='products',
            name='updatedat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='updatedat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
